type ColumnType = 'TEXT' | 'REAL' | 'INTEGER' | 'VARCHAR(255)'

interface ColumnMetadata {
    type: ColumnType;
    otherData?: string;
}

export interface ITransaction {
    id?: number; // Optional if auto-generated by the database
    accountMask: string;
    postedDate: Date;
    description: string;
    details: string;
    amount: number;
    balance: number;
    referenceNumber: string ;
    currency: string;
    type: string;
    createdTime?: Date;
    updatedTime?: Date;
}
export const TransactionMetadata: Record<keyof ITransaction, ColumnMetadata> = {
    id: { type: 'INTEGER', otherData:"AUTO_INCREMENT" },
    referenceNumber: { type: 'VARCHAR(255)', otherData:"UNIQUE"},
    accountMask: { type: 'TEXT' },
    postedDate: { type: 'TEXT' },
    description: { type: 'TEXT' },
    details: { type: 'TEXT' },
    amount: { type: 'REAL' },
    balance: { type: 'REAL' },
    currency: { type: 'TEXT' },
    type: { type: 'TEXT' },
    createdTime: { type: 'TEXT' },
    updatedTime: { type: 'TEXT' }
};
