type ColumnType = 'TEXT' | 'REAL' | 'INTEGER';

interface ColumnMetadata {
    type: ColumnType;
    primaryKey?: boolean;
}
export interface ITransaction {
    id?: number; // Optional if auto-generated by the database
    accountMask: string;
    postedDate: Date;
    description: string;
    details: string;
    amount: number;
    balance: number;
    referenceNumber: string | null;
    currency: string;
    type: string;
    createdTime?: Date;
    updatedTime?: Date;
}
export const TransactionMetadata: Record<keyof ITransaction, ColumnMetadata> = {
    id: { type: 'INTEGER', primaryKey: true },
    accountMask: { type: 'TEXT' },
    postedDate: { type: 'TEXT' },
    description: { type: 'TEXT' },
    details: { type: 'TEXT' },
    amount: { type: 'REAL' },
    balance: { type: 'REAL' },
    referenceNumber: { type: 'TEXT' },
    currency: { type: 'TEXT' },
    type: { type: 'TEXT' },
    createdTime: { type: 'TEXT' },
    updatedTime: { type: 'TEXT' }
};
